# Generated by Django 3.0.6 on 2020-06-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200602_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('genre',),
            },
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='cast',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
    ]
